### PR TITLE
Feature/harsh daniel/vsr page 2

### LINKED ISSUE #19: VSR Form Page 2 - Contact Info, Military Background, and Additional Info
Implement the second page of the VSR form. The Figma design can be found [here](https://www.figma.com/file/jARPdBWD6HutwLFzepjZW1/PAP-Web-Application?type=design&node-id=621-26556&mode=design&t=un8IFXQRfrDt5err-0). The first page has already been developed, so you'll essentially be expanding on the form by adding a second page. The [task writeup](https://github.com/TritonSE/PAP-Inventory-Processing/issues/9) for the VSR form first page describes what work is involved at each layer of the tech stack, but here's a quick summary for this page specifically:
- **MongoDB Database**: Add the necessary fields to our `VSR` data model to include all fields on the 2nd page of the form
- **Backend**:  Add validators for each new field, and update the controller (i.e. route handler) to accept these new fields in the request body, and pass them into the database
- **Frontend**: Build the UI for the 2nd page of the form, and connect it with the backend. Use the field components developed for the 1st page of the form so you don't have to build from scratch. Also, implement the transitioning between pages of the form by clicking the "Back" and "Next" buttons - I'd recommend just having a `useState` for the current page, and showing a different component for the correct page UI based on the current page value.

### PR DESCRIPTION
**Pull request by HarshGurnani**
## Tracking Info

Resolves #19 

## Changes

- Added VSR Page 2 backend and frontend
- Updated MongoDB, added new validators and controllers, and created second page form 

## Testing

- Ran frontend and went to `localhost:3000/vsr`.
- Can see created VSR form in MongoDB after hitting submit button

- TODO

## Confirmation of Change
image

image

- Run the frontend and go to `localhost:3000/vsr`. This should show both existing pages of the VSR form. Use the Next button after filling out the first page to see the second page.
- After hitting Submit on the second page, check MongoDB for newly created VSR object

### CODE REVIEW

**Review by benjaminJohnson2204 — APPROVED** [review]
LGTM! I made a few minor changes but nice work overall, it works great!

**Review by 2s2e — APPROVED** [review]
-I am able to submit an alphabetical phone number and a badly formatted email.
-Other than that everything looks good! Testing instructions work as expected, webpage looks aligned with figma, MongoDB works properly.

**Comment by HarshGurnani** [comment]
Thanks @2s2e , I fixed the issues!

**Review by sydneyzhang18 — APPROVED** [review]
lgtm!

**Pull request merged**
