### PR TITLE
Feature/steven+yoto vsr personal info

### LINKED ISSUE #9: VSR Form - Page 1 (Personal Information)
Implement the first page (Personal Information) of the VSR design on Figma. We'll eventually add the other 2 pages on, with "Next" and "Back" buttons to navigate between them. But for now, just put the "Submit" button on the first page, and have that button submit the form to our backend, so we can test the first page end-to-end.

### Backend
- **DO THIS FIRST** Create a MongoDB database model for a VSR. Look at the Figma design, and/or the VSR PDF if you need it (attached to this issue) to see what fields there are and what data types they should have. For now, only include the fields on the first page of the VSR in the Figma design. The reason this part should be done first is that other tasks (staff table and individual view of VSRs) require this DB model to be created in order for their backend routes to be written
- Create an API route to POST `/api/vsr` to submit a VSR. This route should NOT require the user to be authenticated (authentication is only for staff). On this route, verify that all required fields are present in the request body and meet validation rules (see the Frontend section for examples of validation). I'd recommend using [Express Validator](https://express-validator.github.io/docs/) to validate the request. This is the library used in the TSE Onboarding repo, so feel free to reference that repo as an example of validating request data. If all validation checks pass, create an entry in the VSR database using the data in the request body.

### Frontend
- Put the VSR form on the `/vsr` URL (this might change later)
- Render the layout of the first page, matching the [Figma design](https://www.figma.com/file/jARPdBWD6HutwLFzepjZW1/PAP-Web-Application?type=design&node-id=200-1647&mode=design&t=tO9klt7Btz8fMuUY-0). Create some reusable components for form fields (e.g. text field, multiple choice). I know that not all fields of the same type will look the same, but just do your best to use reusable components
- The text fields can just be input elements, but the multiple-choice fields will need code to listen to when the user clicks on one of the options, and update the UI to show that option as selected (I assume the selected option would have a dark background and white text, but we can clarify with the designers).
- To manage the form fields, validation, submission, etc., I'd recommend using a 3rd-party library. I like [React-hook-form](https://react-hook-form.com/), another option is [Formik](https://formik.org/) or any other library you want to find yourself. Use whatever you prefer.
- When the user clicks the "Submit" button, this should first validate the form data. Ensure that all fields are filled in and meet some reasonable validation rules (e.g. age should be an integer, not "K#MD83nm2", use your best judgment to what validation should be run on each field). If one or more fields fail validation, display an error message on that field indicating what is wrong (e.g. "Age is required", "Age must be an integer").
- If all validation checks succeed, submit the form data to our backend via a POST request to `/api/vsr`.

### PR DESCRIPTION
**Pull request by 2s2e**
## Tracking Info

Resolves #9 

## Changes
-Added a MongoDB schema for storing VSR form submissions
-Set up POST route for VSR
-Added front-end for submitting a VSR
-Added front-end side validation functions (currently unused)

## Testing
-Front-end validation functions were tested using unit tests in frontend/__tests__
-Rest of the features were tested end-to-end:

-Load up both the front end and the back end
-Go to http://localhost:3000/vsr
-Leaving out any required field will result in the field failing to submit
-Providing invalid data, such as inputting strings for age, will result in an error from the back end.
-Submitting a valid form will have it show up in the MongoDB database

This was done various times, with different inputs and leaving different fields empty.

Note that MongoDB may take a few moments to update.

- TODO

## Confirmation of Change
Missing fields
image
image
Error upon invalid input
image

Successful form submission

image
image
image
image

### CODE REVIEW

**Review by benjaminJohnson2204 — APPROVED** [review]
LGTM, I made some minor fixes (mostly CSS) but overall great job!

**Review by sydneyzhang18 — APPROVED** [review]
lgtm! I stress tested a lot and found some bugs that all look good now

**Review by holychickencow — APPROVED** [review]
For the most part it looks good, I have few notes that I'm not sure need to be fixed but I will leave it here case. 

- You are allowed to be "single" but also have a spouse name.
- When you enter that you have 100 children, it states "This field must be a number no greater than 100," even though 100 should be valid.

Aside from these it looks good!

**Comment by benjaminJohnson2204** [comment]
Thanks @holychickencow , nice catches! I just pushed some fixes to address your comments, we're good to merge now!

**Pull request merged**
