### PR TITLE
Feature/sydney vsr table staff view

### LINKED ISSUE #10: VSR Table View for Staff
Create the VSR table view page for staff to see a list of VSRs. Focus on the frontend at first, because the backend route for this task depends on the backend routes and DB models for other tasks being completed. 

### Frontend
- Implement the table view page. See [Figma design](https://www.figma.com/file/jARPdBWD6HutwLFzepjZW1/PAP-Web-Application?type=design&node-id=200-3694&mode=design&t=tO9klt7Btz8fMuUY-0).
- Put this page on the `/staff/vsr` URL
- I'd recommend using the [Material UI Table component](https://mui.com/material-ui/react-table/) for the table itself
- For now, focus on the UI of the page. That is, rendering the title, search bars, refresh & export buttons, and table view itself. Use some hard-coded dummy data in the table for now, and the buttons don't have to do anything yet.

### Backend
- Once our authentication backend routes and VSR database models are done, then we will need an API route to GET `/api/vsr/` that will return a list of all submitted VSRs. This route should require the user to be authenticated and have the `staff` or `admin` role. The frontend will then use this data to populate the VSRs table.
- The "Refresh" button should make the frontend make a new request to the backend to get the VSRs, and then update the table with the new data.
- Searching by keywords and filtering by status will eventually need to be implemented in this route

### PR DESCRIPTION
**Pull request by sydneyzhang18**
## Tracking Info

Resolves #10 

## Changes

- Created frontend on /staff/vsr
- Wrote backend GET route to get all VSRs

## Testing

- Started frontend and viewed page
- Manually tested GET request in terminal

## Confirmation of Change

- Start frontend and backend
- Go to <http://localhost:3000/staff/vsr> and view frontend w/ header, title, and table
- After changes, should be able to see all VSRs in mongo on the table, manually add a VSR, and see the updated VSRs on table

## TODO
- Populate frontend with non-hard coded VSRs from mongo
- Frontend: alignment of "Service Requests" header, font, color of checkbox in header row

### CODE REVIEW

**Review by benjaminJohnson2204 — APPROVED** [review]
LGTM! I integrated the frontend with the backend and made some minor CSS touch-ups to match the design, looks good overall. Great work!

**Comment by Syu125** [comment]
Everything looks good! I just made a very minor change to get the font to show up for the two buttons.

**Review by Syu125 — APPROVED** [review]
Everything looks good! I just made a very minor change to get the font to show up for the two buttons.

**Review by SamvritSrinath — APPROVED** [review]
LGTM! Stress tested with different names, repeat IDs, as well as repeat names and seems to all be ordered correctly. Special Characters for all fields also work as well.

**Pull request merged**
