### PR TITLE
Feature/harsh steven/export vsr bulk

### LINKED ISSUE #31: Export Bulk VSR Data to Spreadsheet
Add the ability for staff/admin users to export all VSR data to a spreadsheet.

# Backend
- Create a new API route like `GET /api/vsr/bulk_export` that exports all VSRs. The route should return an Excel (`.xlsx`) file with the VSRs in it
- See #6 for a list of possible libraries to use for writing to Excel
- For now, you can just export every field of the VSR in the most human-readable/useful format possible (use your judgment), we might take some fields out later

# Frontend
- Connect the "Export" button the VSR table view to your new backend route, so it will call the route and then download the Excel file to the user's device

### PR DESCRIPTION
**Pull request by 2s2e**
## Tracking Info

Resolves #31
## Changes

-Implemented export as pdf feature, which downloads a copy of all vsrs as an excel spreadsheet when the export button is clicked
-Added notifications for exporting VSR

Note: possible bug with furniture items

## Testing

-We logged into the page as a privileged user, and clicked the export button. An excel file should then download, which contains the data for the VSRs. A success notification should also pop up

## Confirmation of Change

image

image
(More columns to the right of the downloaded file)

### CODE REVIEW

**Review by benjaminJohnson2204 — APPROVED** [review]
LGTM! Great work guys! I used this PR to add a few minor unrelated changes & bugfixes. I'll assign 2 other reviewers in today's meeting.

**Comment by Syu125** [comment]
The furniture items are not listed in the spreadsheet-is this something that needs to be fixed?

**Review by Syu125 — APPROVED** [review]
Look good to me!

**Review by yotzkim — APPROVED** [review]
Looks good to me!

**Pull request merged**
